<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Timo Roettger">
<meta name="author" content="Hågard Meyer">
<meta name="dcterms.date" content="2026-03-22">

<title>session09 - exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="MEYER_09_homework_files/libs/clipboard/clipboard.min.js"></script>
<script src="MEYER_09_homework_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="MEYER_09_homework_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="MEYER_09_homework_files/libs/quarto-html/popper.min.js"></script>
<script src="MEYER_09_homework_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MEYER_09_homework_files/libs/quarto-html/anchor.min.js"></script>
<link href="MEYER_09_homework_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MEYER_09_homework_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MEYER_09_homework_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MEYER_09_homework_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MEYER_09_homework_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">session09 - exercises</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Timo Roettger </p>
             <p>Hågard Meyer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="preamble-loading-packages-and-configuration" class="level1">
<h1>Preamble: Loading packages and configuration</h1>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The main <strong>learning goals</strong> of this week’s practical parts are:</p>
<ul>
<li>getting an intuition about the gap between verbal hypotheses and formal hypotheses</li>
</ul>
</section>
<section id="the-data" class="level1">
<h1>The data</h1>
<p>In this dataset, we will be analyzing data from <span class="citation" data-cites="kilpatrick2023random">Kilpatrick, Ćwiek, and Kawahara (<a href="#ref-kilpatrick2023random" role="doc-biblioref">2023</a>)</span>:</p>
<p>In a nutshell, the authors were interested in whether there is a relationship between the form of a word and its meaning by looking at Japanese Pokemon names.</p>
<p>Let’s have a look at the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in the dataset and already remove irrelevant stuff:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pokemon <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'../../data/Japanese_Pokemon_simplified.csv'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">Sum of values</span><span class="st">`</span>, <span class="sc">-</span>Checksum)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check data set:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pokemon</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,865 × 40
   Designation Output Length Evolution     f     T     b     d     g     G     z
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 Official    fuSig…     10         1     1     0     0     1     1     0     0
 2 Official    fuSig…      9        NA     1     0     0     0     1     0     0
 3 Official    fuSig…     10         2     1     0     1     0     1     0     0
 4 Official    hitok…      8         1     0     0     0     0     1     0     0
 5 Official    rizaR…      7        NA     0     0     0     1     0     0     1
 6 Official    rizaR…      8         2     0     0     0     1     0     0     1
 7 Official    zenig…      8         1     0     0     0     0     1     0     1
 8 Official    kameR…      7        NA     0     0     0     0     0     0     0
 9 Official    kameQ…      9         2     0     0     0     0     0     0     0
10 Official    Katap…      7         1     0     0     0     0     0     0     0
# ℹ 1,855 more rows
# ℹ 29 more variables: j &lt;dbl&gt;, p &lt;dbl&gt;, t &lt;dbl&gt;, C &lt;dbl&gt;, k &lt;dbl&gt;, K &lt;dbl&gt;,
#   s &lt;dbl&gt;, S &lt;dbl&gt;, h &lt;dbl&gt;, m &lt;dbl&gt;, M &lt;dbl&gt;, n &lt;dbl&gt;, N &lt;dbl&gt;, r &lt;dbl&gt;,
#   L &lt;dbl&gt;, y &lt;dbl&gt;, w &lt;dbl&gt;, a &lt;dbl&gt;, i &lt;dbl&gt;, u &lt;dbl&gt;, e &lt;dbl&gt;, o &lt;dbl&gt;,
#   Q &lt;dbl&gt;, R &lt;dbl&gt;, X &lt;dbl&gt;, H &lt;dbl&gt;, v &lt;dbl&gt;, P &lt;dbl&gt;, c &lt;dbl&gt;</code></pre>
</div>
</div>
<p>What you see here are the following variables:</p>
<p>Variables:</p>
<p><code>Designation</code>: source of Pokemon name. Official = the official names of Japanese Pokemon; Elicited = elicited names from naive participants.</p>
<p>(<code>pokemonname</code>: Pokemon name in Japanese) removed in simplified data file</p>
<p><code>Output</code>: Pokemon name in transcribed form</p>
<p><code>Length</code>: Amount of phones in name</p>
<p><code>Evolution</code>: Evolution stage of Pokemons: 1 = pre-evolution; 2 = post-evolution, NA = do not evolve</p>
<p><code>f</code> = amount of /f/ sounds in name</p>
<p><code>T</code> = amount of /T/ sounds in name</p>
<p>…</p>
<p>and many more different sounds.</p>
<p>Now imagine researchers want to use this data set to <em>test</em> the following hypothesis:</p>
<p><em>The evolution stage of a Pokemon is reflected in aspects of its Japanese name</em></p>
</section>
<section id="exercise" class="level1">
<h1>Exercise</h1>
<section id="a-preregister-your-analysis" class="level2">
<h2 class="anchored" data-anchor-id="a-preregister-your-analysis">A: Preregister your analysis</h2>
<p>Take the hypothesis and what you know about the data set and its structure to predict a very specific relationship that you can test. You are allowed to look at the dataset, but do not look at concrete relationships that might be a manifestation of the hypothesis.</p>
<section id="my-approach" class="level3">
<h3 class="anchored" data-anchor-id="my-approach">My approach</h3>
<p>Taking the hypothesis given above I instinctively see that it is vague. One aspect I see that is testable is the relationship between evolution stage and length of Japanese name. This can be done simply by predicting the length of Japanese name by the evolution stage, including a random effect for the whether the output is from the Pokemon official name, or an elicited one. Pokemon that cannot evolve are removed. An addition of random effects for both unique Pokemon and speaker for elicited names could have been considered, but, as an equal output does not ensure that it is the same Pokemon, this is not done due to there not being a variable for this.</p>
<p>The task is provided with the LME4 package, so I am assuming we are doing the comparison using this.</p>
</section>
</section>
<section id="b-run-your-preregistered-analysis" class="level2">
<h2 class="anchored" data-anchor-id="b-run-your-preregistered-analysis">B: Run your preregistered analysis</h2>
<p>Run the preregistered analysis made in (A) above and interpret your results relative to the hypothesis.</p>
<section id="my-approach-1" class="level3">
<h3 class="anchored" data-anchor-id="my-approach-1">My approach</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing pokemon that cannot evolve and turning the designation into a factor</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pokemon_clean <span class="ot">&lt;-</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  pokemon <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( <span class="sc">!</span><span class="fu">is.na</span> ( Evolution ) ) <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">Designation =</span> <span class="fu">as.factor</span> ( Designation ) )</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a model to the relationship</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>xmdl <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( Length <span class="sc">~</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>               Evolution <span class="sc">+</span> </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>               (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> pokemon_clean)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a null model to compare it to</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>xmdl_null <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( Length <span class="sc">~</span> </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">1</span> <span class="sc">+</span> </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                      (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> pokemon_clean)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Looking at the model</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(xmdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Length ~ Evolution + (1 | Designation)
   Data: pokemon_clean

REML criterion at convergence: 6631.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.7356 -0.6283 -0.0263  0.4916  6.7640 

Random effects:
 Groups      Name        Variance Std.Dev.
 Designation (Intercept) 0.009479 0.09736 
 Residual                3.728567 1.93095 
Number of obs: 1595, groups:  Designation, 2

Fixed effects:
            Estimate Std. Error t value
(Intercept)  5.72076    0.16867   33.92
Evolution    1.27415    0.09672   13.17

Correlation of Fixed Effects:
          (Intr)
Evolution -0.865</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing the model against a null hypothesis</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(xmdl_null, xmdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: pokemon_clean
Models:
xmdl_null: Length ~ 1 + (1 | Designation)
xmdl: Length ~ Evolution + (1 | Designation)
          npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
xmdl_null    3 6796.3 6812.4 -3395.2    6790.3                         
xmdl         4 6633.3 6654.8 -3312.6    6625.3 165.06  1  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Looking at the output we see that by moving up a stage in evolution we get an increase of about ~1.27 in name length. Mean length of pre-evolution Pokemon is predicted to be ~6.99 ( ~5.72 + ~1.27 ) and for post-evolution Pokemon we get ~8.27 ( ~5.72 + ( 2 * ~1.27 ) ). A P-value of less than 0.001 gives some credibility to this claim.</p>
</section>
</section>
<section id="c-show-contradicting-results" class="level2">
<h2 class="anchored" data-anchor-id="c-show-contradicting-results">C: Show contradicting results</h2>
<p>Now explore the data and find two alternative way to test the research hypothesis that yield convincing results that go in opposite directions based of your findings in (A). Justify all your choices verbally after the fact.</p>
<section id="my-approach-2" class="level3">
<h3 class="anchored" data-anchor-id="my-approach-2">My approach</h3>
<p>Exploring the dataset I find some concerning details (in addition to the lack of specifier noted in A). As an example, I can find an output “rizaRdo” noted with NA in Evolution to mark “do not evolve”. I suspect this is リザード (Hepburn “rizādo”) who does evolve into リザードン (Hepburn “rizādon”). Not having a species definition in the data set, I have to analyse what I am given. I choose to look at the relationship between Evolution and 1. the proportion of unique sounds in the Japanese name 2. the proportion of consonants in the Japanese name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Additional mutations</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>pokemon_mutated <span class="ot">&lt;-</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  pokemon_clean <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">unique_characters =</span> <span class="fu">rowSums</span> ( <span class="fu">select</span> ( .,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                                                  f<span class="sc">:</span>c )</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                                         <span class="sc">&gt;</span> <span class="dv">0</span> ) ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">proportion_unique_characters =</span> unique_characters <span class="sc">/</span> Length ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">sum_vowels =</span> <span class="fu">rowSums</span> ( <span class="fu">select</span> ( .,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                                           a,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                                           i,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>                                           u,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                                           e,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                                           o,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                                           R) ) ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">proportion_vowels =</span> sum_vowels <span class="sc">/</span> Length ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> ( <span class="at">proportion_consonants =</span> <span class="dv">1</span> <span class="sc">-</span> proportion_vowels )</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a model to predict proportion of unique characters based on Evolution</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>ymdl <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( proportion_unique_characters <span class="sc">~</span> </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>                 Evolution <span class="sc">+</span> </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>                 (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> pokemon_mutated)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Fittin null model</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>ymdl_null <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( proportion_unique_characters <span class="sc">~</span> </span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">1</span> <span class="sc">+</span> </span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>                      (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> pokemon_mutated)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Showing model</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ymdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: proportion_unique_characters ~ Evolution + (1 | Designation)
   Data: pokemon_mutated

REML criterion at convergence: -1800

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.7573 -0.5121  0.0674  1.1105  1.3202 

Random effects:
 Groups      Name        Variance Std.Dev.
 Designation (Intercept) 0.00000  0.000   
 Residual                0.01876  0.137   
Number of obs: 1595, groups:  Designation, 2

Fixed effects:
             Estimate Std. Error t value
(Intercept)  0.876627   0.010896  80.451
Evolution   -0.028717   0.006859  -4.187

Correlation of Fixed Effects:
          (Intr)
Evolution -0.949
optimizer (nloptwrap) convergence code: 0 (OK)
boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparing model to null</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ymdl_null, ymdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: pokemon_mutated
Models:
ymdl_null: proportion_unique_characters ~ 1 + (1 | Designation)
ymdl: proportion_unique_characters ~ Evolution + (1 | Designation)
          npar     AIC     BIC logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
ymdl_null    3 -1794.2 -1778.1 900.10   -1800.2                         
ymdl         4 -1809.7 -1788.2 908.83   -1817.7 17.454  1  2.943e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting model to predict proportion of consonants based on Evolution</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>zmdl <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( proportion_consonants <span class="sc">~</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                 Evolution <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                 (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> pokemon_mutated)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting null model</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>zmdl_null <span class="ot">&lt;-</span> <span class="fu">lmer</span> ( proportion_consonants <span class="sc">~</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">1</span> <span class="sc">+</span> </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>                      (<span class="dv">1</span> <span class="sc">|</span> Designation ),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> pokemon_mutated)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Showing model</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(zmdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: proportion_consonants ~ Evolution + (1 | Designation)
   Data: pokemon_mutated

REML criterion at convergence: -3643.5

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.0294 -0.5808  0.2171  0.4866  2.6586 

Random effects:
 Groups      Name        Variance  Std.Dev.
 Designation (Intercept) 6.179e-05 0.007861
 Residual                5.888e-03 0.076734
Number of obs: 1595, groups:  Designation, 2

Fixed effects:
             Estimate Std. Error t value
(Intercept)  0.488300   0.008270  59.042
Evolution   -0.010200   0.003844  -2.654

Correlation of Fixed Effects:
          (Intr)
Evolution -0.701</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparing model to null</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(zmdl_null, zmdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: pokemon_mutated
Models:
zmdl_null: proportion_consonants ~ 1 + (1 | Designation)
zmdl: proportion_consonants ~ Evolution + (1 | Designation)
          npar     AIC     BIC logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)   
zmdl_null    3 -3648.6 -3632.5 1827.3   -3654.6                        
zmdl         4 -3653.6 -3632.1 1830.8   -3661.6 7.0024  1    0.00814 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>My justification for choosing to look at the proportion of unique characters is that this can be interpreted as an increase in complexity in the Japanese name. If evolution marks an increase in features and / or power, we might expect an increase in complexity or diversity to reflect that. The model does, however, provide a negative trend for proportion of unique character as a Pokemon evolves ( -~0.029 with a P-value of less than 0.001). This indicates that Pokemon that can evolve have more variation in characters than post-evolution Pokemon.</p>
<p>My justification for choosing to look at the proportion of consonants in the Japanese name is that consonants can be perceived as harsher and / or stronger than vowels. This can be thought to mirror the pre- and post-evolution Pokemon change given the presumed change in power. Again the model predicts a negative trend here ( ~-0.010 with a P-value of ~0.008) suggesting that there is a lower proportion of consonants in the post-evolution.</p>
</section>
</section>
<section id="d-researcher-degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="d-researcher-degrees-of-freedom">D: Researcher degrees of freedom</h2>
<p>Note down all dimensions of researcher degrees of freedom that make the mapping of the hypothesis onto your data analysis vague. How many possible combinations can you think of?</p>
<section id="my-approach-3" class="level3">
<h3 class="anchored" data-anchor-id="my-approach-3">My approach</h3>
<p>I will do this by taking the hypothesis as sections and judging those.</p>
<blockquote class="blockquote">
<p><em>The evolution stage of a Pokemon is reflected in aspects of its Japanese name</em></p>
</blockquote>
<p><em>The evolution stage</em> is vague as is. Mainly, what happens with Pokemon that cannot evolve? These can be interpreted as irrelevant (not part of an evolution stage), possibly joined with pre-evolution Pokemon (they have not evolved) or joined with the post-evolution Pokemon (they cannot evolve further). Looking at the Evolution column it gets worse. I have mentioned that some Pokemon seem to show wrong information about their ability to evolve. Furthermore, prior knowledge of Pokemon tells me that Pokemon can have more categories than are present in the dataset. at the very least we have:</p>
<ol type="1">
<li>Pokemon that do not evolve and have not evolved from anything</li>
<li>Pokemon that can evolve and have not evolved from anything</li>
<li>Pokemon that can evolve and have evolved from something</li>
<li>Pokemon that cannot evolve and have evolved from something</li>
</ol>
<p><em>Pokemon</em> also lends itself to some vagueness here. Looking at the data set we have two different designations for these, namely <em>Official</em> (presumably a written official name) and <em>Elicited</em> (as by a naive speaker). This ties together with the wording <em>Japanese name</em>. A researcher can either join these as one group, or choose to focus on just one of them. While these are likely connected, they are not guaranteed to give the same outputs.</p>
<p>Finally <em>aspect</em> is likely the most vague term. A name can have an almost infinite number of aspects, like intonation, stress, connotations to other words etc. Even within the given data set, a researcher can choose to look at length of name, any one of the output sounds individually or any number of combination and orderings of these. The number of combinations here is still astronomical and each of those combinations can be combined again with decisions made in relation to my previous paragraphs decisions.</p>
<p>Importantly these choices are not trivial. While they might lead to similar conclusions, they just as well might not.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<!-- References will auto-populate in the refs div below -->
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-kilpatrick2023random" class="csl-entry" role="listitem">
Kilpatrick, Alexander James, Aleksandra Ćwiek, and Shigeto Kawahara. 2023. <span>“Random Forests, Sound Symbolism and Pok<span>é</span>mon Evolution.”</span> <em>PloS One</em> 18 (1): e0279350.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>